### ISSUE TITLE
have database keep track of mL left in containers

### ISSUE THREAD

**Issue by jbriede** [jbriede/seniorDesign#5]
function to
- update mL on refill
- subtract mL each time a drink is dispensed
- keep track of mL and send error when low
- Make drink unavailable when ingredient is empty

**Comment by collinpc** [comment]
How do I get the value when the button is pressed?

**Comment by jbriede** [comment]
There are two events in the server file, dispenseSingleDrink and stopDispense. The database should take the time (time.time()) when the dispenseSingleDrink event occurs and when stopDispense occurs. subtract the second time from the first time to get the amount of time the button was pressed. Then multiply that by the mL/s value to get the number of mL dispensed.

**Comment by jbriede** [comment]
Done it
